# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: local
    hooks:
    -   id: yapf
        name: yapf
        entry: yapf -i
        language: python
        types:
        -   python
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        exclude: 'test_*'

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    -   id: mypy
        exclude: 'test_*'

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
